# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Redgadgets
email: info@redgadgets.com
description: > # this means to ignore newlines until "baseurl:"
  Latest technology at your fingertips.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redgadgets.com" # the base hostname & protocol for your site
enforce_ssl: 'redgadgets.com'
#footer
built-by: webjeda

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/


#social
facebook: https://facebook.com/webjeda
quora: https://quora.com/sharathdt
twitter: https://twitter.com/@webjeda
github: https://github.com/webjeda

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/Redgadgets-331713717021812/
fb-page-title: webjeda

analytics: 'UA-56952216-1'

sass:
  style: compressed

gems: [jekyll-paginate, jekyll-seo-tag]

